[Recipe/nntrainer] Add recipe for nntrainer
nnstreamer/meta-neural-network pull request #56
Opened 2020-10-16 08:32 UTC by anyj0527

- Add recipes and patches for iniparser and openblas which nntrainer requires
- This recipe for nntrainer fetch the main branch of nntrainer.git and packaging it
- You could check the unittest binaries at `/usr/lib/nntrainer/bin/applications/unittest_*`

- TODO: Add package `nntrainer-application` and resolve deps

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

2020-10-16 08:36 UTC, wooksong commented
@anyj0527 I merged #55. 

Q: Do you need a bitbake recipe for iniparser instead of the recipe already there?

2020-10-19 07:41 UTC, wooksong commented on recipes-devtools/iniparser/iniparser_4.1.bb
> +SUMMARY = "The iniParser library is a simple C library offering INI file parsing services (both reading and writing)."
@anyj0527 This recipe is just a copy of meta-openembedded/meta-oe/recipes-support/iniparser. Why are you putting this recipe into meta-neural-network? We can use iniparser by adding a layer dependency on meta-oe.

2020-10-19 07:42 UTC, wooksong requested changes
Please remove recipes that are already there.

2020-10-21 03:32 UTC, anyj0527 commented
@wooksong` Sorry for late it's my bad. I missed removing it, thank you pointing out!

2020-10-21 05:58 UTC, wooksong commented on recipes-devtools/openblas/openblas_0.3.10.bb
> +    https://github.com/xianyi/OpenBLAS/archive/v${PV}.tar.gz;downloadfilename=${BP}.tar.gz \
Unfortunately, the new version has been just released :( But I am OK with 0.3.10:)

Instead of ```recipes-devtools/openblas```, how about using recipes-blas(?) or whatsoever? It is your package so that pick a name whatever you like (again I am also OK with recipe-devtools).

2020-10-21 07:44 UTC, anyj0527 commented on recipes-devtools/openblas/openblas_0.3.10.bb
> +    https://github.com/xianyi/OpenBLAS/archive/v${PV}.tar.gz;downloadfilename=${BP}.tar.gz \
recipes-blas/openblas seems great. I move the path. The OpenBLAS is saying that v0.3.11 is unstable. I'll keep the version to 0.3.10 when the new version turns out to be stable, I'll bump up the version.

2020-10-22 07:19 UTC, wooksong approved these changes
Confirmed that it is possible to build ```nntrainer``` with the recipe in this PR.

2020-10-22 07:20 UTC, merged